POST http://localhost:5002/usuarios/crear
Content-Type: application/json

{
    "nombre" : "Captain Gonax",
    "email" : "captain@example.com",
    "contra" : "password123",
    "rol" : "ESPECTADOR",
    "estado" : "ACTIVO"
}
